### Tampilkan semua data
GET http://localhost:8080/api/account
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDg5NDA0MDYsImlhdCI6MTc0ODg1NDAwNiwiaXNzIjoiY3AyYiIsInN1YiI6MSwidG9rZW5fdmVyc2lvbiI6M30.P-C6HoTScKsj3OAm7IBd697r5-VjRrMufAbB8Sa-kvM
##

### Tambah data baru
POST http://localhost:8080/api/account
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDg5NDA0MDYsImlhdCI6MTc0ODg1NDAwNiwiaXNzIjoiY3AyYiIsInN1YiI6MSwidG9rZW5fdmVyc2lvbiI6M30.P-C6HoTScKsj3OAm7IBd697r5-VjRrMufAbB8Sa-kvM

{
    "name": "Subagja andaraloji",
    "descriptions": "Edi supono ti jawa barat"
}
##

### Tampilkan data By ID
GET http://localhost:8080/api/account/90
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDg5NDA0MDYsImlhdCI6MTc0ODg1NDAwNiwiaXNzIjoiY3AyYiIsInN1YiI6MSwidG9rZW5fdmVyc2lvbiI6M30.P-C6HoTScKsj3OAm7IBd697r5-VjRrMufAbB8Sa-kvM
##

### Update data
PUT http://localhost:8080/api/account/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDg5NDA0MDYsImlhdCI6MTc0ODg1NDAwNiwiaXNzIjoiY3AyYiIsInN1YiI6MSwidG9rZW5fdmVyc2lvbiI6M30.P-C6HoTScKsj3OAm7IBd697r5-VjRrMufAbB8Sa-kvM
{
    "name": "BBBBBBBBBBBBBB"
}
##

### Delete data
DELETE http://localhost:8080/api/account/100
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDg5NDA0MDYsImlhdCI6MTc0ODg1NDAwNiwiaXNzIjoiY3AyYiIsInN1YiI6MSwidG9rZW5fdmVyc2lvbiI6M30.P-C6HoTScKsj3OAm7IBd697r5-VjRrMufAbB8Sa-kvM
##