### Tampilkan semua data
GET http://localhost:8080/api/category
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDg4ODMxOTUsImlhdCI6MTc0ODc5Njc5NSwiaXNzIjoieW91ci1hcHAtbmFtZSIsInN1YiI6MX0.r1GAPqrVRILkxxX9kwpOcG5KfpZ4JPddt_k-kjFh9eM
##

### Tambah data baru
POST http://localhost:8080/api/category
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDg4ODMxOTUsImlhdCI6MTc0ODc5Njc5NSwiaXNzIjoieW91ci1hcHAtbmFtZSIsInN1YiI6MX0.r1GAPqrVRILkxxX9kwpOcG5KfpZ4JPddt_k-kjFh9eM

{
    "name": "Jajan arloji",
    "type": "pengeluaran",
    "descriptions": "Sok jajan kumur - kumur"
}
##

### Tampilkan data By ID
GET http://localhost:8080/api/category/9000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDg4ODMxOTUsImlhdCI6MTc0ODc5Njc5NSwiaXNzIjoieW91ci1hcHAtbmFtZSIsInN1YiI6MX0.r1GAPqrVRILkxxX9kwpOcG5KfpZ4JPddt_k-kjFh9eM
##

### Update data
PUT http://localhost:8080/api/category/90
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDg4ODMxOTUsImlhdCI6MTc0ODc5Njc5NSwiaXNzIjoieW91ci1hcHAtbmFtZSIsInN1YiI6MX0.r1GAPqrVRILkxxX9kwpOcG5KfpZ4JPddt_k-kjFh9eM

{
    "name": "gaji",
    "type": "pemasukan",
    "descriptions": "Gaji kecil sangat"
}
##

### Delete data
DELETE http://localhost:8080/api/category/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDg4ODMxOTUsImlhdCI6MTc0ODc5Njc5NSwiaXNzIjoieW91ci1hcHAtbmFtZSIsInN1YiI6MX0.r1GAPqrVRILkxxX9kwpOcG5KfpZ4JPddt_k-kjFh9eM
##