basePath: /
definitions:
  dto.AccountDTO:
    properties:
      ID:
        type: integer
      Name:
        type: string
    type: object
  dto.BalanceDTO:
    properties:
      Balance:
        type: number
      ID:
        type: integer
    type: object
  dto.CategoryDTO:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  dto.UserDTO:
    properties:
      ID:
        type: integer
      Name:
        type: string
    type: object
  request.AccountRequest:
    properties:
      descriptions:
        type: string
      name:
        type: string
    required:
    - name
    type: object
  request.AuthRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  request.CategoryRequest:
    properties:
      descriptions:
        type: string
      name:
        type: string
      type:
        enum:
        - pemasukan
        - pengeluaran
        - pindah
        type: string
    required:
    - name
    - type
    type: object
  request.TransactionRequest:
    properties:
      account_id:
        type: integer
      amount:
        type: number
      category_id:
        type: integer
      date:
        type: string
      descriptions:
        type: string
      target_account_id:
        type: integer
      type:
        enum:
        - pemasukan
        - pengeluaran
        - pindah
        type: string
    required:
    - account_id
    - amount
    - category_id
    - date
    - type
    type: object
  response.APIResponse:
    properties:
      code:
        type: integer
      data: {}
      errors: {}
      message:
        type: string
      meta: {}
      status:
        type: string
    type: object
  response.AccountListSwaggerResponse:
    properties:
      code:
        type: integer
      data:
        items:
          $ref: '#/definitions/response.AccountResponse'
        type: array
      message:
        type: string
    type: object
  response.AccountResponse:
    properties:
      Balance:
        $ref: '#/definitions/dto.BalanceDTO'
      BalanceID:
        type: integer
      Descriptions:
        type: string
      ID:
        type: integer
      Name:
        type: string
    type: object
  response.BalanceListSwaggerResponse:
    properties:
      code:
        type: integer
      data:
        items:
          $ref: '#/definitions/response.BalanceResponse'
        type: array
      message:
        type: string
    type: object
  response.BalanceResponse:
    properties:
      Account:
        $ref: '#/definitions/dto.AccountDTO'
      AccountID:
        type: integer
      Balance:
        type: number
      ID:
        type: integer
    type: object
  response.CategoryListSwaggerResponse:
    properties:
      code:
        type: integer
      data:
        items:
          $ref: '#/definitions/response.CategoryResponse'
        type: array
      message:
        type: string
    type: object
  response.CategoryResponse:
    properties:
      Descriptions:
        type: string
      ID:
        type: integer
      Name:
        type: string
      Type:
        type: string
    type: object
  response.TransactionListSwaggerResponse:
    properties:
      code:
        type: integer
      data:
        items:
          $ref: '#/definitions/response.TransactionResponse'
        type: array
      message:
        type: string
    type: object
  response.TransactionResponse:
    properties:
      Account:
        $ref: '#/definitions/dto.AccountDTO'
      AccountID:
        type: integer
      Amount:
        type: number
      Category:
        $ref: '#/definitions/dto.CategoryDTO'
      CategoryID:
        type: integer
      Date:
        type: string
      Descriptions:
        type: string
      ID:
        type: integer
      TargetAccount:
        $ref: '#/definitions/dto.AccountDTO'
      TargetAccountID:
        type: integer
      Type:
        type: string
      User:
        $ref: '#/definitions/dto.UserDTO'
      UserID:
        type: integer
    type: object
info:
  contact: {}
  description: Simply cp2b system
  title: BE CP2B - REST API Docs
  version: "1.0"
paths:
  /api/Category/{id}:
    put:
      consumes:
      - application/json
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      - description: Category data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.CategoryRequest'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/response.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.APIResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.APIResponse'
      security:
      - BearerAuth: []
      summary: Update Category
      tags:
      - Category
  /api/account:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/response.AccountListSwaggerResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            items:
              $ref: '#/definitions/response.APIResponse'
            type: array
      security:
      - BearerAuth: []
      summary: Get all accounts
      tags:
      - Account
    post:
      consumes:
      - application/json
      parameters:
      - description: Account data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.AccountRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.AccountListSwaggerResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.APIResponse'
      security:
      - BearerAuth: []
      summary: Create new account
      tags:
      - Account
  /api/account/{id}:
    delete:
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/response.APIResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.APIResponse'
      security:
      - BearerAuth: []
      summary: Delete account
      tags:
      - Account
    get:
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.AccountListSwaggerResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.APIResponse'
      security:
      - BearerAuth: []
      summary: Get account by ID
      tags:
      - Account
    put:
      consumes:
      - application/json
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      - description: Account data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.AccountRequest'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/response.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.APIResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.APIResponse'
      security:
      - BearerAuth: []
      summary: Update account
      tags:
      - Account
  /api/balance:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/response.BalanceListSwaggerResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            items:
              $ref: '#/definitions/response.APIResponse'
            type: array
      security:
      - BearerAuth: []
      summary: Get all balances
      tags:
      - Balance
  /api/category:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/response.CategoryListSwaggerResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            items:
              $ref: '#/definitions/response.APIResponse'
            type: array
      security:
      - BearerAuth: []
      summary: Get all categories
      tags:
      - Category
    post:
      consumes:
      - application/json
      parameters:
      - description: Category data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.CategoryRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.CategoryListSwaggerResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.APIResponse'
      security:
      - BearerAuth: []
      summary: Create new category
      tags:
      - Category
  /api/category/{id}:
    delete:
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/response.APIResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.APIResponse'
      security:
      - BearerAuth: []
      summary: Delete category
      tags:
      - Category
    get:
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CategoryListSwaggerResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.APIResponse'
      security:
      - BearerAuth: []
      summary: Get category by ID
      tags:
      - Category
  /api/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Login data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.AuthRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.APIResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.APIResponse'
      summary: Login
      tags:
      - Auth
  /api/logout:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.APIResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.APIResponse'
      security:
      - BearerAuth: []
      summary: Logout user
      tags:
      - Auth
  /api/transaction:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/response.TransactionListSwaggerResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            items:
              $ref: '#/definitions/response.APIResponse'
            type: array
      security:
      - BearerAuth: []
      summary: Get all transactions
      tags:
      - Transaction
    post:
      consumes:
      - application/json
      parameters:
      - description: Transaction data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.TransactionRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.TransactionListSwaggerResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.APIResponse'
      security:
      - BearerAuth: []
      summary: Create new transaction
      tags:
      - Transaction
  /api/transaction/{id}:
    delete:
      parameters:
      - description: Transaction ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/response.APIResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.APIResponse'
      security:
      - BearerAuth: []
      summary: Delete transaction
      tags:
      - Transaction
    get:
      parameters:
      - description: Transaction ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.TransactionListSwaggerResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.APIResponse'
      security:
      - BearerAuth: []
      summary: Get transaction by ID
      tags:
      - Transaction
    put:
      consumes:
      - application/json
      parameters:
      - description: Transaction ID
        in: path
        name: id
        required: true
        type: integer
      - description: Transaction data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.TransactionRequest'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/response.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.APIResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.APIResponse'
      security:
      - BearerAuth: []
      summary: Update transaction
      tags:
      - Transaction
schemes:
- https
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
